### ISSUE TITLE
Error: can't specify None for path argument

### ISSUE THREAD

**Issue by rudvfaden** [ketan/BeautifyLatex#3] opened 2015-09-21 16:38 UTC
Just shows up when I press the key binding.

**Comment by ketan** [comment] 2015-09-21 17:38
duplicate of #2

**Comment by rudvfaden** [comment] 2015-09-21 18:20
I put it in my path. I still get the same error.

**Comment by ketan** [comment] 2015-09-22 01:32
What OS are you on? How did you add it to `PATH` and how do you start sublime?

**Comment by rudvfaden** [comment] 2015-09-22 04:04
OSX. I added the path to my zhsrc file. I open sublime with spotlight

**Comment by ketan** [comment] 2015-09-22 04:18
Adding to `.zshrc` and opening with spotlight does not apply the path to programs launched using spotlight. I'd suggest either (a) opening sublime from the terminal `open -a /Applications/Sublime\ Text.app/` or (b) using [Fix Mac Path](https://packagecontrol.io/packages/Fix%20Mac%20Path) sublime plugin

I'll probably update the README with these instructions.

**Comment by rudvfaden** [comment] 2015-09-22 15:00
Okay. I'm not really sure what should be in what path. I installed Fix mac path and launched from the terminal. The problems persists.

**Comment by yrammos** [comment] 2015-12-07 18:20
At least on the latest versions of OSX and TeXLive, `which indentlatex.pl` fails whereas `which indentlatex`succeeds. This is because the Perl file is normally outside the $PATH, and the symlink that is reachable from the $PATH does not include the `.pl` extension.

**Comment by ketan** [comment] 2015-12-08 03:56
> At least on the latest versions of OSX and TeXLive, which indentlatex.pl fails whereas which indentlatexsucceeds. This is because the Perl file is normally outside the $PATH, and the symlink that is reachable from the $PATH does not include the .pl extension.

I think I understand your point. Would you like to submit a PR for this line — https://github.com/ketan/BeautifyLatex/blob/master/beautify_latex.py#L55

**Comment by yrammos** [comment] 2015-12-09 11:07
@ketan, false alarm. Starting the editor from the terminal (`subl`) sets up the environment properly. [Fix Mac Path](https://packagecontrol.io/packages/Fix%20Mac%20Path) also works on my end.

**Comment by ketan** [comment] 2015-12-09 11:23
Closing based on @yrammos's comment (https://github.com/ketan/BeautifyLatex/issues/3#issuecomment-163190294)

**Closed as completed by ketan** 2015-12-09 11:23 UTC

**Comment by 5chdn** [comment] 2016-04-23 20:57
I'm having the same issue on linux and I don't understand how Sublime deals with the `$PATH`.

```
 ~ $ which latexindent
/usr/bin/latexindent
 ~ $ ll /usr/bin/latexindent 
0 lrwxrwxrwx 1 root root 56 Nov 14 21:50 /usr/bin/latexindent -> /usr/share/texmf-dist/scripts/latexindent/latexindent.pl
```

`latexindent.pl` is available but why do I get `Error: can't specify None for path argument` in Sublime Text 3 running BeautifyLatex?
